package dk.apaq.nets.payment;

import java.util.Arrays;

import org.apache.commons.codec.DecoderException;
import org.apache.commons.codec.binary.Hex;

/**
 *
 * @author krog
 */
public class PGTMHeader {

    public static final int HEADER_LENGTH = 32;
    private static final String DEFAULT_IDENTITY = "0000524800022000000000000032000000000000000000000000";
    private static final int BITS_IN_BYTE = 8;
    private static final int FULL_BYTE = 0XFF;
    
    private final short length;
    private final String identity;
    private final String networkResponseCode;

    /**
     * Creates a new instance.
     *
     * @param length The length of the payload exluding the this header.
     * @param networkResponseCode The response code
     */
    public PGTMHeader(int length, String networkResponseCode) {
        this(length, DEFAULT_IDENTITY, networkResponseCode);
    }

    /**
     * Creates a new instance.
     *
     * @param length The length of the payload exluding the this header.
     * @param identity A custom identity.
     * @param networkResponseCode The response code
     */
    public PGTMHeader(int length, String identity, String networkResponseCode) {
        this.length = (short) (length + HEADER_LENGTH);
        this.identity = identity;
        this.networkResponseCode = networkResponseCode;
    }

    /**
     * Retrieves the total length of the data being sent including this header.
     *
     * @return The length.
     */
    public int getLength() {
        return length;
    }

    /**
     * Retrieves the identity.
     *
     * @return The identity.
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * Retrieves the reposne code.
     *
     * @return The reponse code.
     */
    public String getNetworkResponseCode() {
        return networkResponseCode;
    }

    /**
     * Builds a bytearray from the header.
     *
     * @return The generated bytearray.
     */
    public byte[] toByteArray() {
        try {
            byte[] lengthData = new byte[]{(byte) (length >>> BITS_IN_BYTE), (byte) (length & FULL_BYTE)};
            byte[] identityData = Hex.decodeHex(identity.toCharArray());
            byte[] networkData = Hex.decodeHex(networkResponseCode.toCharArray());
            byte[] fixed = Hex.decodeHex("0000".toCharArray());
            byte[] data = new byte[HEADER_LENGTH];
            //CHECKSTYLE:OFF
            System.arraycopy(lengthData, 0, data, 0, 2);
            System.arraycopy(identityData, 0, data, 2, 26);
            System.arraycopy(networkData, 0, data, 28, 2);
            System.arraycopy(fixed, 0, data, 30, 2);
            //CHECKSTYLE:ON
            return data;
        } catch (DecoderException ex) {
            throw new IllegalStateException("The header contains data that cannot be converted to bytes.", ex);
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final PGTMHeader other = (PGTMHeader) obj;
        if (this.length != other.length) {
            return false;
        }
        if ((this.identity == null) ? (other.identity != null) : !this.identity.equals(other.identity)) {
            return false;
        }
        if ((this.networkResponseCode == null) ? (other.networkResponseCode != null) : !this.networkResponseCode.equals(other.networkResponseCode)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        //CHECKSTYLE:OFF
        int hash = 7;
        hash = 79 * hash + this.length;
        hash = 79 * hash + (this.identity != null ? this.identity.hashCode() : 0);
        hash = 79 * hash + (this.networkResponseCode != null ? this.networkResponseCode.hashCode() : 0);
        //CHECKSTYLE:ON
        return hash;
    }

    /**
     * Generates a PGTMHeader from byte array.
     * @param data The byte array.
     * @return The PGTMHeader
     */
    public static PGTMHeader fromByteArray(byte[] data) {
        if (data.length != HEADER_LENGTH) {
            throw new IllegalArgumentException("Length of data must be 32 bytes");
        }
        //CHECKSTYLE:OFF
        byte[] lengthData = Arrays.copyOfRange(data, 0, 2);
        byte[] identityData = Arrays.copyOfRange(data, 2, 28);
        byte[] networkData = Arrays.copyOfRange(data, 28, 30);
        byte[] fixedData = Arrays.copyOfRange(data, 30, 32);
        //CHECKSTYLE:ON
        short length = (short) (lengthData[1] & FULL_BYTE | (lengthData[0] << BITS_IN_BYTE));
        length -= HEADER_LENGTH; //We take away the length of the header - 32 bytes
        String identity = new String(Hex.encodeHex(identityData));
        String networkResponseCode = new String(Hex.encodeHex(networkData));

        return new PGTMHeader(length, identity, networkResponseCode);
    }
}
